TinyXml: ticpp::Attribute Class Reference
ticpp::Attribute Class Reference
Wrapper around TiXmlAttribute.
#include <ticpp.h>